# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 562)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbDirect = QtWidgets.QComboBox(self.centralWidget)
        self.cmbDirect.setObjectName("cmbDirect")
        self.cmbDirect.addItem("")
        self.cmbDirect.addItem("")
        self.verticalLayout.addWidget(self.cmbDirect)
        self.cmbWeight = QtWidgets.QComboBox(self.centralWidget)
        self.cmbWeight.setObjectName("cmbWeight")
        self.cmbWeight.addItem("")
        self.cmbWeight.addItem("")
        self.verticalLayout.addWidget(self.cmbWeight)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.graphMatrix = QtWidgets.QTableView(self.centralWidget)
        self.graphMatrix.setMaximumSize(QtCore.QSize(16777204, 16777215))
        self.graphMatrix.setSizeIncrement(QtCore.QSize(0, 0))
        self.graphMatrix.setBaseSize(QtCore.QSize(7, 14))
        self.graphMatrix.setDragEnabled(False)
        self.graphMatrix.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.graphMatrix.setAlternatingRowColors(True)
        self.graphMatrix.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.graphMatrix.setIconSize(QtCore.QSize(1, 0))
        self.graphMatrix.setTextElideMode(QtCore.Qt.ElideLeft)
        self.graphMatrix.setShowGrid(True)
        self.graphMatrix.setGridStyle(QtCore.Qt.SolidLine)
        self.graphMatrix.setSortingEnabled(False)
        self.graphMatrix.setObjectName("graphMatrix")
        self.verticalLayout.addWidget(self.graphMatrix)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnNext = QtWidgets.QPushButton(self.centralWidget)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 887, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuTasks = QtWidgets.QMenu(self.menuBar)
        self.menuTasks.setObjectName("menuTasks")
        self.menu2 = QtWidgets.QMenu(self.menuTasks)
        self.menu2.setObjectName("menu2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProgram = QtWidgets.QAction(MainWindow)
        self.actionProgram.setObjectName("actionProgram")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(MainWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(MainWindow)
        self.action10.setObjectName("action10")
        self.action11 = QtWidgets.QAction(MainWindow)
        self.action11.setObjectName("action11")
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")
        self.action13 = QtWidgets.QAction(MainWindow)
        self.action13.setObjectName("action13")
        self.action14 = QtWidgets.QAction(MainWindow)
        self.action14.setObjectName("action14")
        self.action15 = QtWidgets.QAction(MainWindow)
        self.action15.setObjectName("action15")
        self.action16_2 = QtWidgets.QAction(MainWindow)
        self.action16_2.setObjectName("action16_2")
        self.action17_2 = QtWidgets.QAction(MainWindow)
        self.action17_2.setObjectName("action17_2")
        self.action18_2 = QtWidgets.QAction(MainWindow)
        self.action18_2.setObjectName("action18_2")
        self.action19 = QtWidgets.QAction(MainWindow)
        self.action19.setObjectName("action19")
        self.action20 = QtWidgets.QAction(MainWindow)
        self.action20.setObjectName("action20")
        self.action21 = QtWidgets.QAction(MainWindow)
        self.action21.setObjectName("action21")
        self.BFSaction = QtWidgets.QAction(MainWindow)
        self.BFSaction.setObjectName("BFSaction")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.IDAaction = QtWidgets.QAction(MainWindow)
        self.IDAaction.setObjectName("IDAaction")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuInfo.addAction(self.actionProgram)
        self.menuInfo.addAction(self.actionAuthor)
        self.menu2.addAction(self.BFSaction)
        self.menu2.addAction(self.actionA)
        self.menu2.addAction(self.IDAaction)
        self.menuTasks.addAction(self.menu2.menuAction())
        self.menuTasks.addAction(self.action3)
        self.menuTasks.addAction(self.action4)
        self.menuTasks.addAction(self.action5)
        self.menuTasks.addAction(self.action6)
        self.menuTasks.addAction(self.action7)
        self.menuTasks.addAction(self.action8)
        self.menuTasks.addAction(self.action9)
        self.menuTasks.addAction(self.action10)
        self.menuTasks.addAction(self.action11)
        self.menuTasks.addAction(self.action12)
        self.menuTasks.addAction(self.action13)
        self.menuTasks.addAction(self.action14)
        self.menuTasks.addAction(self.action15)
        self.menuTasks.addAction(self.action16_2)
        self.menuTasks.addAction(self.action17_2)
        self.menuTasks.addAction(self.action18_2)
        self.menuTasks.addAction(self.action19)
        self.menuTasks.addAction(self.action20)
        self.menuTasks.addAction(self.action21)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTasks.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Графоид"))
        self.cmbDirect.setItemText(0, _translate("MainWindow", "Направленный"))
        self.cmbDirect.setItemText(1, _translate("MainWindow", "Ненаправленный"))
        self.cmbWeight.setItemText(0, _translate("MainWindow", "Нагруженный"))
        self.cmbWeight.setItemText(1, _translate("MainWindow", "Ненагруженный"))
        self.btnCancel.setText(_translate("MainWindow", "← Отменить"))
        self.btnNext.setText(_translate("MainWindow", "→ Дальше"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuInfo.setTitle(_translate("MainWindow", "?"))
        self.menuTasks.setTitle(_translate("MainWindow", "Задачи"))
        self.menu2.setTitle(_translate("MainWindow", "2. Поиск пути"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionProgram.setText(_translate("MainWindow", "О программе"))
        self.actionAuthor.setText(_translate("MainWindow", "Об авторе"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.action3.setText(_translate("MainWindow", "3. Алгоритм Дейкстры и близкие к нему"))
        self.action4.setText(_translate("MainWindow", "4. Эксцентриситет, радиус, диаметр и степени"))
        self.action5.setText(_translate("MainWindow", "5. Изоморфизм графов"))
        self.action6.setText(_translate("MainWindow", "6. Связность графа"))
        self.action7.setText(_translate("MainWindow", "7.  Дополнение для графа"))
        self.action8.setText(_translate("MainWindow", "8. Бинарные операции над графами"))
        self.action9.setText(_translate("MainWindow", "9. Планарность графа"))
        self.action10.setText(_translate("MainWindow", "10. Восстановление графа из вектора"))
        self.action11.setText(_translate("MainWindow", "11. Экстремальные графы"))
        self.action12.setText(_translate("MainWindow", "12. Деревья и минимальное остовное дерево"))
        self.action13.setText(_translate("MainWindow", "13. Задача о цикле"))
        self.action14.setText(_translate("MainWindow", "14. Раскраска графа"))
        self.action15.setText(_translate("MainWindow", "15. Задача о свадьбах"))
        self.action16_2.setText(_translate("MainWindow", "16. Дополнение 2-комплекса"))
        self.action17_2.setText(_translate("MainWindow", "17. Восстановление 2-комплекса из вектора"))
        self.action18_2.setText(_translate("MainWindow", "18. Экстремальные 2-комплексы"))
        self.action19.setText(_translate("MainWindow", "19. Задача коммивояжёра"))
        self.action20.setText(_translate("MainWindow", "20. Доминирование и покрывающее множество"))
        self.action21.setText(_translate("MainWindow", "21. Эффективность алгоритмов поиска пути"))
        self.BFSaction.setText(_translate("MainWindow", "BFS"))
        self.actionA.setText(_translate("MainWindow", "A*"))
        self.IDAaction.setText(_translate("MainWindow", "Iterative deepening A"))
