# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from ui.sourse.qgraphview import QGraphView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 562)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphView = QGraphView(self.centralWidget)
        self.graphView.setObjectName("graphView")
        self.horizontalLayout_6.addWidget(self.graphView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbDirect = QtWidgets.QComboBox(self.centralWidget)
        self.cmbDirect.setObjectName("cmbDirect")
        self.cmbDirect.addItem("")
        self.cmbDirect.addItem("")
        self.verticalLayout.addWidget(self.cmbDirect)
        self.cmbWeight = QtWidgets.QComboBox(self.centralWidget)
        self.cmbWeight.setObjectName("cmbWeight")
        self.cmbWeight.addItem("")
        self.cmbWeight.addItem("")
        self.verticalLayout.addWidget(self.cmbWeight)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblMatrSize = QtWidgets.QLabel(self.centralWidget)
        self.lblMatrSize.setObjectName("lblMatrSize")
        self.horizontalLayout_4.addWidget(self.lblMatrSize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.spbMatrSize = QtWidgets.QSpinBox(self.centralWidget)
        self.spbMatrSize.setObjectName("spbMatrSize")
        self.horizontalLayout_4.addWidget(self.spbMatrSize)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableWidgetMatr = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetMatr.setMaximumSize(QtCore.QSize(16777204, 16777215))
        self.tableWidgetMatr.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetMatr.setBaseSize(QtCore.QSize(7, 14))
        self.tableWidgetMatr.setDragEnabled(False)
        self.tableWidgetMatr.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidgetMatr.setAlternatingRowColors(True)
        self.tableWidgetMatr.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidgetMatr.setIconSize(QtCore.QSize(1, 0))
        self.tableWidgetMatr.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidgetMatr.setShowGrid(True)
        self.tableWidgetMatr.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetMatr.setRowCount(7)
        self.tableWidgetMatr.setColumnCount(7)
        self.tableWidgetMatr.setObjectName("tableWidgetMatr")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidgetMatr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidgetMatr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatr.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetMatr.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetMatr.setItem(1, 0, item)
        self.tableWidgetMatr.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetMatr.horizontalHeader().setDefaultSectionSize(42)
        self.tableWidgetMatr.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidgetMatr.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetMatr.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetMatr.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetMatr.verticalHeader().setDefaultSectionSize(25)
        self.tableWidgetMatr.verticalHeader().setMinimumSectionSize(26)
        self.tableWidgetMatr.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetMatr.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidgetMatr)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnNext = QtWidgets.QPushButton(self.centralWidget)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_6.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 887, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuTasks = QtWidgets.QMenu(self.menuBar)
        self.menuTasks.setObjectName("menuTasks")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProgram = QtWidgets.QAction(MainWindow)
        self.actionProgram.setObjectName("actionProgram")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuInfo.addAction(self.actionProgram)
        self.menuInfo.addAction(self.actionAuthor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTasks.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmbDirect.setItemText(0, _translate("MainWindow", "Направленный"))
        self.cmbDirect.setItemText(1, _translate("MainWindow", "Ненаправленный"))
        self.cmbWeight.setItemText(0, _translate("MainWindow", "Нагруженный"))
        self.cmbWeight.setItemText(1, _translate("MainWindow", "Ненагруженный"))
        self.lblMatrSize.setText(_translate("MainWindow", "Размерность матрицы"))
        self.tableWidgetMatr.setSortingEnabled(False)
        item = self.tableWidgetMatr.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidgetMatr.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetMatr.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetMatr.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetMatr.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidgetMatr.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetMatr.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetMatr.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        __sortingEnabled = self.tableWidgetMatr.isSortingEnabled()
        self.tableWidgetMatr.setSortingEnabled(False)
        self.tableWidgetMatr.setSortingEnabled(__sortingEnabled)
        self.btnCancel.setText(_translate("MainWindow", "← Отменить"))
        self.btnNext.setText(_translate("MainWindow", "→ Дальше"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuInfo.setTitle(_translate("MainWindow", "?"))
        self.menuTasks.setTitle(_translate("MainWindow", "Задачи"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionProgram.setText(_translate("MainWindow", "О программе"))
        self.actionAuthor.setText(_translate("MainWindow", "Об авторе"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
